Import('env')
myenv = env.Clone()
src = ['thread.c']
# if myenv['ARCH'] == 'xtensa':
#     myenv.Append(
#         CPPPATH = [
#             myenv['BUILDDIR'].abspath + '/buildroot/build/uclibc-1.0.12/libc/sysdeps/linux'
#         ]
#     )
#     src += ['clone.S']

myenv.LxProgram(myenv, target = 'thread', source = src, libs = ['pthread'])
