Import('env')
myenv = env.Clone()
myenv.Append(
    CPPPATH = [
        '#buildroot/output/build/uclibc-7bf35c8b7d4a1f97174eb49f47f33946b282114c/libc/sysdeps/linux/xtensa/'
    ]
)
myenv.LxProgram(myenv, target = 'thread', source = ['clone.S', 'thread.c'], libs = ['pthread'])
