Import('env')
myenv = env.Clone()
src = ['thread.c']
if myenv['ARCH'] == 'xtensa':
    myenv.Append(
        CPPPATH = [
            myenv['BUILDDIR'].abspath + '/buildroot/build/uclibc-7bf35c8b7d4a1f97174eb49f47f33946b282114c/libc/sysdeps/linux/xtensa/'
        ]
    )
    src += ['clone.S']

myenv.LxProgram(myenv, target = 'thread', source = src, libs = ['pthread'])
