#!/bin/sh

# check if "RUN_BENCH" has been written to 0x3000000
str=`dd if=/dev/mem ibs=1024 skip=$((48*1024)) count=1 2>/dev/null | dd bs=1 count=9 2>/dev/null`
if [ "$str" != "RUN_BENCH" ]; then
    exit 0
fi

/bench.sh
