#!/bin/sh

# check if "RUN_BENCH" has been written to 0x17FFFC00
str=`dd if=/dev/mem ibs=1024 skip=393215 count=1 2>/dev/null`
if [[ "$str" != "RUN_BENCH"* ]]; then
    exit 0
fi

echo "Running benchmark \"${str:9}\"..."
/bench/bench.sh "${str:9}"
