#!/bin/sh

# check if a command has been written to 0x3000000
str=`dd if=/dev/mem ibs=1024 skip=$((48*1024)) count=1 2>/dev/null | xargs`
cmd=${str#CMD=}
if [ $cmd = $str ]; then
    exit 0
fi

/fsbench.sh "$cmd"
