#!/bin/sh

# check if "RUN_FSBENCH" has been written to 0x3000000
str=`dd if=/dev/mem ibs=1024 skip=$((48*1024)) count=1 2>/dev/null | dd bs=1 count=11 2>/dev/null`
if [ "$str" != "RUN_FSBENCH" ]; then
    exit 0
fi

echo ">=== Starting benchmarks ==="

strace /bench/write /tmp/test $((1024 * 16)) 1>/dev/null

echo "===="

/bench/stracetime /bench/write /tmp/test $((1024 * 16)) 1>/dev/null

echo "<=== Benchmarks done ==="
