Import('env')

myenv = env.Clone()

myenv['CPPPATH'] += ['#libs/leveldb/include']

myenv['CXXFLAGS'] = [
    # use the same flags as for M³
    '-std=c++14',
    '-fno-strict-aliasing',
    '-fno-omit-frame-pointer',
    '-fno-threadsafe-statics',
    '-fno-stack-protector',
    '-O2',
    '-DNDEBUG',
    '-flto',
    '-U_FORTIFY_SOURCE',
    '-D_GNU_SOURCE',
]
if myenv['ARCH'] == 'riscv64':
    myenv['CXXFLAGS'] += [
        '-march=rv64imafdc',
        '-mabi=lp64',
    ]

myenv['LINKFLAGS'] = [
    # like above, same link flags as on M³
    '-fno-stack-protector',
    '-O2',
    '-flto',
    '-static',
    '-Wl,--build-id=none',
]
if myenv['ARCH'] == 'riscv64':
    myenv['LINKFLAGS'] += [
        '-march=rv64imafdc',
        '-mabi=lp64',
        '-Wl,-z,max-page-size=4096',
        '-Wl,-z,common-page-size=4096',
    ]

myenv.LxProgram(myenv, target = 'leveldb', source = 'leveldb.cc', libs = ['leveldb', 'pthread'])
